title: SPEAR-FLP (Forward Looking Projections Documentation and Outreach
subtitle: "Flexible Large-Ensemble Platform"
name: "SPEAR-FLP"
description: "Documentation, presentations, and outreach for the SPEAR Flexible Large-Ensemble Platform."
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
permalink: pretty

minimal_mistakes_skin: "default"  # or "air", "contrast"


