title: SPEAR-Forward Looking Projections (FLP) Documentation and Outreach
name: "SPEAR-FLP"
description: "Documentation, presentations, and outreach for the SPEAR FLP."
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
permalink: pretty

minimal_mistakes_skin: "default"  # or "air", "contrast"

plugins:
  - jekyll-include-cache
  


