title: Documentation and Outreach
name: "SPEAR-Forward Looking Projections (FLP)
description: "Documentation, presentations, and outreach for the SPEAR FLP."
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
permalink: pretty

minimal_mistakes_skin: "default"  # or "air", "contrast"
url: "https://noaa-gfdl.github.io"
baseurl: "/spear-flp"

plugins:
  - jekyll-include-cache
include:
  - _pages
  


